export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";
